shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from django.conf import settings

from products.views import *  
from users.views import *  
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'products', ProductAPIView)
router.register(r'basket', BasketAPIView, basename='basket')
router.register(r'entrance', UserAuthAPIView, basename='entrance')
router.register(r'profile', UserProfileAPIView)    

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
# --------------------------------API-------------------------------#
    path('api/', include(router.urls)),
    path('api/shop_auth/', include('rest_framework.urls')),  #подключение авторизации в drf
    path('api/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),#для входа пользователя по токену адрес будет: auth/token/login/ 
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import user_login, registration, profile, logout_view

app_name = "users"

urlpatterns = [
    path('login/', user_login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout_view, name='logout'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

    
class User(AbstractUser):
    image = models.ImageField(upload_to='user_images', null=True, blank=True)

users/forms.py
from django.contrib.auth.forms import AuthenticationForm, UserChangeForm, UserCreationForm
from django import forms
from users.models import User

class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder' : 'Введите имя пользователя'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder' : 'Введите пароль'}))

    class Meta:
        model = User
        fields = ('username', 'password')

class UserRegistrationForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder' : 'Введите имя'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder' : 'Введите фамилию'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder' : 'Введите имя'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs = {'placeholder' : 'Введите почту'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder' : 'Введите пароль'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder' : 'Подтвердите пароль'}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

class UserProfileForm(UserChangeForm):
    first_name = forms.CharField(widget=forms.TextInput())
    last_name = forms.CharField(widget=forms.TextInput())
    image = forms.ImageField(widget=forms.FileInput(), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'readonly' : True}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'readonly' : True}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

users/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.urls import reverse

from users.forms import UserRegistrationForm, UserProfileForm, UserLoginForm

from products.models import Basket
from .serializer import UserLoginSerializer, UserRegistrationSerializer, UserProfileSerializer, UserBasketSerializer
from rest_framework import viewsets
from rest_framework.decorators import action
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAdminUser, IsAuthenticated, AllowAny
from rest_framework.authtoken.models import Token
from .models import User

def registration(request):
        # 1. Если запрос POST - обрабатываем форму
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)           #Создать форму с данными
        if form.is_valid():
            user = form.save()          #Сохранить пользователя
            login(request, user)            #Если данные валидны, сохраняем пользователя и выполняем вход с помощью функции login        
            return redirect("users:login")  #Перенаправить на страницу входа после регистрации 
            
    # 2. Если GET - показать пустую форму
    else:
        form = UserRegistrationForm()       #Создать пустую форму
    context = { 'form' : form }
    return render(request, "users/registration.html", context)

def user_login(request):
    form = UserLoginForm(data=request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            #Получение данных из формы
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)     #Проверяет, есть ли пользователь с таким логином/паролем в базе.
        if user is not None:
            login(request, user)         #Создает сессию пользователя (авторизует).
            return redirect("index")
    context = { 'form' : form }
    return render(request, "users/user_login.html", context)
#--------------------------------API-------------------------------#
class UserAuthAPIView(viewsets.ViewSet):  #не прописываю queryset, .... Значит ссылка api/entrance/ не будет работать
    @action(detail=False, methods=['post'], permission_classes=(AllowAny,))
    def registration(self, request):
        serializer = UserRegistrationSerializer(data=request.data)  #создаю экземпляр сериализатора с данными из запроса
        serializer.is_valid(raise_exception=True)       #Сериализатор преобразует эти данные в объект Python и начинает валидацию
        user = serializer.save()  #сохранение в бд
        token, created = Token.objects.get_or_create(user=user)     #Создаёт токен для нового пользователя
        return Response({'user' : UserProfileSerializer(user).data,
                         'token' : token.key})          
    @action(detail=False, methods=['post'], permission_classes=(AllowAny,))
    def login(self, request):
        serializer = UserLoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = serializer.validated_data
        token, create = Token.objects.get_or_create(user=user)
        return Response({'user' : UserProfileSerializer(user).data,
                         'token' : token.key})
#--------------------------------API-------------------------------#

@login_required     #встроенный декоратор - проверяет, авторизован ли пользователь. Если пользователь не вошёл в систему, он будет автоматически перенаправлен на страницу входа.
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)  #последняя переменная нужна для загрузки фото профиля
        if form.is_valid():
            form.save()
            return redirect("users:profile")
    else:
        form = UserProfileForm(instance=request.user)       #при GET-запросе форма заполняется данными из существующего профиля
    
    baskets = Basket.objects.filter(user=request.user)
    total_sum = sum(basket.sum() for basket in baskets)
    total_quantity = sum(basket.quantity for basket in baskets)

    context = {
        'form' : form,
        'baskets' : Basket.objects.filter(user=request.user),
        'total_sum' : total_sum,
        'total_quantity' : total_quantity,
        }
    return render(request, 'users/profile.html', context)
#--------------------------------API-------------------------------#
class UserProfileAPIView(viewsets.ModelViewSet):
    permission_classes = (IsAuthenticated,)
    queryset = User.objects.all()
    serializer_class = UserProfileSerializer

    @action(methods=['put', 'get'], detail=False)
    def profile(self, request):
        user = request.user #Текущий пользователь
        if request.method == 'GET':
            serializer = UserProfileSerializer(user)
            return Response(serializer.data) 
        elif request.method == 'PUT':
            serializer = UserProfileSerializer(request.user, data=request.data, partial=True)  #partial=True разрешает частичное обновление
            serializer.is_valid(raise_exception=True)
            serializer.save()
            return Response(serializer.data) 
    
    @action(methods=['get'], detail=False)
    def user_basket(self, request):
        baskets = Basket.objects.filter(user=request.user)
        total_sum = sum(basket.sum() for basket in baskets)
        total_quantity = sum(basket.quantity for basket in baskets) 
        serializer = UserBasketSerializer({
            'total_sum' : total_sum,
            'total_quantity' : total_quantity,
            'items' : [{
                'id' : basket.id,
                'product' : basket.product.name,
                'quantity' : basket.quantity,
                'price' : basket.product.price
            } for basket in baskets]
        })
        return Response(serializer.data)
#--------------------------------API--------------------------------#



@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))       

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store - Авторизация</title>
</head>
<body>
        {% block content %}{% endblock %}
</body>
</html>

users/templates/users/profile.html
{% extends "users/base.html" %} {% load static %} {% block content %}

<div class="header-bar">
  <h4>Профиль</h4>
</div>
<div>
  <img
    src="{% if user.image and user.image.url %}{{ user.image.url }}
    {% else %}{% static 'vendor/img/users/default_avatar.jpg' %}{% endif %}" height="100" width="100"
  />
</div>

<form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div>
    <label for="{{ form.first_name.id_for_label }}">Имя</label>
    {{ form.first_name }}
  </div>
  <div>
    <label for="{{ form.last_name.id_for_label }}">Фамилия</label>
    {{ form.last_name }}
  </div>
  <div>
    <label for="{{ form.image.id_for_label }}">Выберите изображение</label>
    {{ form.image }}
  </div>
  <div>
    <label for="{{ form.username.id_for_label }}">Имя пользователя</label>
    {{ form.username }}
  </div>
  <div>
    <label for="{{ form.email.id_for_label }}">Адрес электронной почты</label>
    {{ form.email }}
  </div>
  <div><button type="submit">Сохранить</button></div>
</form>

<div>{% include 'products/baskets.html' %}</div>


{% endblock %}

users/templates/users/registration.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
<h2>Регистрация</h2>
<form action="{% url 'users:registration' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}

    <button type="submit"> Подтвердить </button>
</form>

<p><a href="{% url 'users:login' %}"> Уже есть аккаунт? Авторизоваться</a></p>

{% endblock %}

users/templates/users/user_login.html
{% extends "users/base.html" %}
{% load static %}

{% block content %}
{% if messages or form.non_field_errors %}
    <div class=
    "{% if messages %} alert-success {% else %} alert-warning {% endif %}">
        {% if messages %}
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        {% else %}
            {{ form.non_field_errors }}
        {% endif %}
    </div>
    {% endif %}
<h2>Вход</h2>
<form action="{% url 'users:login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit"> Войти </button>
</form>
    <p>Нет аккаунта? <a href="{% url 'users:registration' %}"> Авторизоваться </a></p>


{% endblock %}