orders/urls.py
from django.urls import path
from orders.views import order

app_name = 'orders'

urlpatterns = [
    path('order/', order, name='order'),
]

products/urls.py
from django.urls import path

from products.views import products, basket_add, basket_remove
from products.views import ProductAPIView

app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:category_id>', products, name='category'),
    path('page/<int:page_number>', products, name='paginator'),
    path('basket/add/<int:product_id>', basket_add, name='basket_add'),
    path('basket/remove/<int:basket_id>', basket_remove, name='basket_remove'),
# --------------------------------API-------------------------------#
    # path('productlist/', ProductAPIView.as_view({'get' : 'list'})),
    # path('productlist/<int:pk>/', ProductAPIView.as_view({'put' : 'update'})),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static

from django.conf import settings

from products.views import *  
from users.views import *  
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'products', ProductAPIView)
router.register(r'basket', BasketAPIView, basename='basket')
router.register(r'entrance', UserAuthAPIView, basename='entrance')
router.register(r'profile', UserProfileAPIView)    

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('orders/', include('orders.urls', namespace='orders')),
# --------------------------------API-------------------------------#
    path('api/', include(router.urls)),
    path('api/shop_auth/', include('rest_framework.urls')),  #подключение авторизации в drf
    path('api/auth/', include('djoser.urls')),
    re_path(r'^auth/', include('djoser.urls.authtoken')),#для входа пользователя по токену адрес будет: auth/token/login/ 
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from users.views import user_login, registration, profile, logout_view

app_name = "users"

urlpatterns = [
    path('login/', user_login, name='login'),
    path('registration/', registration, name='registration'),
    path('profile/', profile, name='profile'),
    path('logout/', logout_view, name='logout'),
]

products/models.py
from django.db import models

# from django.core.cache import cache

from orders.models import Order

class ProductsCategory(models.Model):
    name = models.CharField(max_length=128, unique=True)
    description = models.TextField(null=True, blank=True)
    def __str__(self):
        return f"Категория: {self.name}"

    # @classmethod
    # def get_all_cached(cls):
    #     categories = cache.get('all_categories')
    #     if not categories:
    #         categories = list(cls.objects.all())
    #         cache.set('all_categories', categories, 60*15)
    #     return categories

    # def __str__(self):
    #     return f"{self.name}"

class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')
    category = models.ForeignKey(to=ProductsCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f"Продукт: {self.name} | Категория: {self.category}"

class Basket(models.Model):
    user = models.ForeignKey(to='users.User', on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Корзина: {self.user.email} | Продукт: {self.product.name}"
    
    def sum(self):
        return self.product.price * self.quantity

products/views.py
from rest_framework import generics, viewsets 
from rest_framework.viewsets import GenericViewSet
from rest_framework.decorators import action
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAdminUser, IsAuthenticated
from rest_framework.authentication import TokenAuthentication
from .permissions import IsAdminOrReadOnly
from .models import Product, ProductsCategory, Basket
from .serializers import ProductSerializer, BasketSerializer
from rest_framework.views import APIView   #главный класс DRF, связывает запрос с его методом
from rest_framework.response import Response
from django.shortcuts import render, redirect, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator

# from django.views.decorators.cache import cache_page

def index(request):
    context = {'title' : 'Store'}

    return render(request, 'products/index.html', context)


# @cache_page(60* 15) # Кэшируем на 15 минут
def products(request, category_id = None, page_number=1):
    if category_id:         #если user нажимает на определенную категорию, выводятся только товары из выбранной категории
        category = ProductsCategory.objects.get(id = category_id)
        products = Product.objects.filter(category=category)
    else:
        products = Product.objects.all()

    paginator = Paginator(products, 3)
    products_paginator = paginator.page(page_number)

    context = {
        'title' : 'Store - Каталог',
        'categories' : ProductsCategory.objects.all(),
        'products' : products_paginator,
    }
    return render(request, 'products/products.html', context)

#--------------------------------API-------------------------------#
class ProductAPIView(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    permission_classes = (IsAuthenticatedOrReadOnly, IsAdminOrReadOnly)   #IsAuthenticatedOrReadOnly, IsAdminOrReadOnly, IsAuthenticated
#   authentication_classes = (TokenAuthentication,)

#action позволяет внутри данного(товары) представления добавить новый маршрут(например категории)
    @action(methods=['get'], detail=True)  #detail=True означает что получаем одну категорию и ссылка выглядит так: api/products/1/category/
    def category(self, request, pk=None):
        categories = ProductsCategory.objects.get(pk=pk)
        #return Response({'category' : [c.name for c in category]})
        return Response({'category' : categories.name})
#--------------------------------API-------------------------------#

@login_required              #позволяет не зарегистрированному пользователю добавить товар в корзину
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)                                #кладем продукт в корзину
    baskets = Basket.objects.filter(user=request.user, product=product)         #берем все корзины пользователя с определенным продуктом

    if not baskets.exists():
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = baskets.first()
        basket.quantity +=1
        basket.save()
    # return redirect('products:index')
    return HttpResponseRedirect(request.META['HTTP_REFERER']) 

@login_required
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    if basket.quantity>1:
        basket.quantity -=1
        basket.save()
    else:
        basket.delete()
    # return render('users:profile')
    return HttpResponseRedirect(request.META['HTTP_REFERER']) 

#--------------------------------API-------------------------------#
class BasketAPIView(viewsets.ViewSet):
    # queryset = Basket.objects.all()
    # serializer_class = BasketSerializer
    # permission_classes = (IsAuthenticated,)  #если не атворизован, то нельзя ни читать, ни исправлять

    #маршрут для добавления товара
    #api/basket/basket_add/id
    @action(methods=['post'], detail=False, url_path='basket_add/(?P<product_id>[^/.]+)')
    def basket_add(self, request, product_id=None):
        try:
            product = Product.objects.get(id=product_id)
            baskets = Basket.objects.filter(user=request.user, product=product)
            if not baskets.exists():
                Basket.objects.create(user=request.user, product=product, quantity=1)
            else:
                basket = baskets.first()
                basket.quantity +=1
                basket.save()
            return Response({'status' : 'Товар добавлен'})
        except Product.DoesNotExist:
            return Response({'error' : 'Товар не найден'})

    #маршрут для удаления товара
    #api/basket/pk(id=43)/basket_remove/
    @action(methods=['post'], detail=True)
    def basket_remove(self, request, pk=None):
        basket = self.get_object()
        if basket.quantity>1:
            basket.quantity -=1
            basket.save()
        else:
            basket.delete()
        return Response({'status' : 'Товар удалён'})

products/templates/products/base.html
{% load static  %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
       <!-- Шапка -->
    <header>
        <h1>Мой магазин</h1>
    </header>
    <div>
        <ul>
            <li><a href="{% url 'users:profile' %}">Профиль</a></li>
            <li><a href="{% url 'users:logout' %}">Выйти</a></li>
            {% if user.is_superuser or user.is_staff %}
            <li><a href="{% url 'admin:index' %}">Админ панель</a></li>
            {% endif %}
        </ul>
    </div>

    <!-- Основное содержимое -->
    <main>
        {% block content %}
        <!-- Сюда подставится содержимое из index.html и products.html -->
        {% endblock %}
    </main>
</body>
</html>

products/templates/products/baskets.html
{% if baskets %}
<div>
    <h2>Корзина</h2>
    <p>{{ total_quantity }}</p>
</div>

{% for basket in baskets %}
<div>
    <h4><strong>{{ basket.product.name }}</strong></h4>
    <p>{{ basket.product.description }}</p>
    <p>{{ basket.quantity }}</p>
    <p>{{ basket.sum }} руб.</p>
    <a href="{% url 'products:basket_remove' basket.id %}">Удалить товар</a>
</div>
{% endfor %}

<div>
    <p>Итого:</p>
    <p>{{ total_sum }} руб.</p>
</div>

{% else %}
<h4>Корзина пуста</h4>

{% endif %}

<form action="{% url 'orders:order' %}">
    {% csrf_token %}
    <button type="submit">Оформить заказ</button>
</form>

products/templates/products/index.html
{% extends "products/base.html" %}
 {% load static %} 

{% block content %}
<section>
  <h1>Store</h1>
  <p>Качественные товары на Store. Скидка -30% при первом заказе</p>

  <button id="" type="button">
    <a href="{% url 'products:index' %}"> Начать покупки </a>
  </button>
</section>

{% endblock %}

products/templates/products/products.html
{% extends "products/base.html" %} 
{% block content %}

<!-- {% load cache %}

{% cache 900 sidebar %} -->
<section>
  <ul>
    {% for category in categories %}
    <li>
      <a href="{% url 'products:category' category.id %}">
        {{ category.name }}
      </a>
    </li>
    {% endfor %}
  </ul>
</section>
<!-- {% endcache %} -->

<section>
  <div class="product-grid">
    {% for product in products %}
    <div class="product-card">
      <div class="product-image">
        <img
          src="{{ product.image.url }}"
          alt="{{ product.name }}"
          width="100"
          height="100"
        />
      </div>

      <div class="product-name">
        <h3 class="product-info">
          <a href="#"> {{ product.name }} </a>
        </h3>

        <p class="product-price">{{ product.price }} руб.</p>

        <p class="product-description">{{ product.description }}</p>

        <div>
          <form
            action="{% url 'products:basket_add' product.id %}"
            method="post"
          >
            {% csrf_token %}
            <button type="submit">Отправить в корзину</button>
          </form>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</section>

<div>
  <ul>
    <li>
      {% if products.has_previous %}
      <a href="{% url 'products:paginator' products.previous_page_number %}">Предыдущая</a>
      {% endif %}
    </li>
    {% for page in products.paginator.page_range %} 
    <li>
        <a href="{% url 'products:paginator' page %}">{{ page }}</a>
    </li>
    {% endfor %}
    <li>
      {% if products.has_next %}
      <a href="{% url 'products:paginator' products.next_page_number %}">Следующая</a>
      {% endif %}
    </li>
  </ul>
</div>

{% endblock %}